name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

# Add top-level permissions
permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/campus-molndal-cloh24/cloud-applications-advanced:${{ github.ref_name }}

  deploy_to_azure_container_apps:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name cloudapplicationadvanced-${{ github.ref_name }} \
            --resource-group DockerDemoRG \
            --image ghcr.io/campus-molndal-cloh24/cloud-applications-advanced:${{ github.ref_name }}
